// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4qN0kwYbH708-vP7z9S0ORufOsh5zdxs',
    appId: '1:700617602773:web:7b2e115dfa1bdb1daa145c',
    messagingSenderId: '700617602773',
    projectId: 'hdhntgt',
    authDomain: 'hdhntgt.firebaseapp.com',
    databaseURL: 'https://hdhntgt-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hdhntgt.firebasestorage.app',
    measurementId: 'G-Z2J2PN7T32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFhBI-u4eue-X3yOJ07rCR00Tqt5hOqFM',
    appId: '1:700617602773:android:8f80aef171c65a7eaa145c',
    messagingSenderId: '700617602773',
    projectId: 'hdhntgt',
    databaseURL: 'https://hdhntgt-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hdhntgt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5coZsDX98iRR1fmDFmT8xhBnWvumW4lw',
    appId: '1:700617602773:ios:74132b50e4eb9334aa145c',
    messagingSenderId: '700617602773',
    projectId: 'hdhntgt',
    databaseURL: 'https://hdhntgt-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hdhntgt.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5coZsDX98iRR1fmDFmT8xhBnWvumW4lw',
    appId: '1:700617602773:ios:74132b50e4eb9334aa145c',
    messagingSenderId: '700617602773',
    projectId: 'hdhntgt',
    databaseURL: 'https://hdhntgt-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hdhntgt.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4qN0kwYbH708-vP7z9S0ORufOsh5zdxs',
    appId: '1:700617602773:web:39287cbc5c892bcaaa145c',
    messagingSenderId: '700617602773',
    projectId: 'hdhntgt',
    authDomain: 'hdhntgt.firebaseapp.com',
    databaseURL: 'https://hdhntgt-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hdhntgt.firebasestorage.app',
    measurementId: 'G-XSZKP1G9YE',
  );
}
